#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$ROOT_DIR"

# shellcheck disable=SC1091
source "${ROOT_DIR}/infra/host/common.sh"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}Starting choruz development environment...${NC}"

# Respect host-native port overrides so worktree-local stacks do not collide.
API_PORT="${CHORUZ_API_PORT}"
PIPELINE_PORT="${CHORUZ_PIPELINE_METRICS_PORT}"
WEB_PORT="${CHORUZ_WEB_PORT}"
DB_HOST="${CHORUZ_PG_HOST:-127.0.0.1}"
DB_PORT="${CHORUZ_PG_PORT}"
DB_NAME="${CHORUZ_PG_DB}"
DB_USER="${CHORUZ_PG_USER}"
DB_URL="postgres://${DB_USER}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
API_PROCESS_REGEX="${CHORUZ_API_GATEWAY_PROCESS_REGEX}"
PIPELINE_PROCESS_REGEX="${CHORUZ_PIPELINE_PROCESS_REGEX}"
BACKEND_READY_ATTEMPTS=80
BACKEND_READY_TIMEOUT_SECONDS=$((BACKEND_READY_ATTEMPTS / 4))
API_RECORD="${RUNTIME_DIR}/api-gateway.pid"
PIPELINE_RECORD="${RUNTIME_DIR}/choruz-pipeline.pid"
WATCHDOG_RECORD="${RUNTIME_DIR}/watchdog.pid"
export CHORUZ_OPERATOR_WORKSPACE CHORUZ_OPERATOR_USER CHORUZ_SESSION_TTL_HOURS
export CHORUZ_PG_HOST CHORUZ_PG_PORT CHORUZ_PG_USER CHORUZ_PG_DB
# Harness paths are configured in the host environment file as well as the
# invoking shell.  Export them before starting the long-lived services so a
# local upgrade can intentionally select a newer CLI than the first `PATH`
# match (notably Codex).
export CHORUZ_CLAUDE_BINARY="${CHORUZ_CLAUDE_BINARY:-}"
export CHORUZ_CODEX_BINARY="${CHORUZ_CODEX_BINARY:-}"
export CHORUZ_PI_BINARY="${CHORUZ_PI_BINARY:-}"
export CHORUZ_GROK_BINARY="${CHORUZ_GROK_BINARY:-}"
export CHORUZ_OPENCODE_BINARY="${CHORUZ_OPENCODE_BINARY:-opencode}"

# Kill any leftover processes on our ports before starting.
for port in "$API_PORT" "$PIPELINE_PORT"; do
  pids=$(lsof -ti ":$port" 2>/dev/null || true)
  for p in $pids; do
    if process_matches_worktree "$p" "${API_PROCESS_REGEX}|${PIPELINE_PROCESS_REGEX}"; then
      cmd=$(ps -p "$p" -o comm= 2>/dev/null || true)
      stop_owned_process "$p" "${API_PROCESS_REGEX}|${PIPELINE_PROCESS_REGEX}" || true
      echo -e "${YELLOW}  Stopped stale $cmd (PID $p) on port $port${NC}"
    fi
  done
done
sleep 1

# Ensure .choruz-runtime directory exists
mkdir -p .choruz-runtime

# Auto-generate dev credentials on first run, persist to .choruz-runtime/.dev.env (chmod 600).
# Skipped for any var already exported in the parent shell (your override wins).
DEV_ENV_FILE=".choruz-runtime/.dev.env"
REMOTE_CONTROL_ENV_FILE=".choruz-runtime/.remote-control.env"
CHORUZ_SESSION_SECRET_OVERRIDE="$(printenv CHORUZ_SESSION_SECRET 2>/dev/null || true)"
CHORUZ_OPERATOR_PASSWORD_OVERRIDE="$(printenv CHORUZ_OPERATOR_PASSWORD 2>/dev/null || true)"
HAS_DEV_ENV=false
if [ -f "$DEV_ENV_FILE" ]; then
  HAS_DEV_ENV=true
fi
if [ -f "$REMOTE_CONTROL_ENV_FILE" ]; then
  # Local deployment coordinates only; this file is gitignored.
  # shellcheck disable=SC1090
  source "$REMOTE_CONTROL_ENV_FILE"
fi
if [ -f "$DEV_ENV_FILE" ]; then
  # shellcheck disable=SC1090
  source "$DEV_ENV_FILE"
fi
if [ -n "$CHORUZ_SESSION_SECRET_OVERRIDE" ]; then
  CHORUZ_SESSION_SECRET="$CHORUZ_SESSION_SECRET_OVERRIDE"
fi
if [ -n "$CHORUZ_OPERATOR_PASSWORD_OVERRIDE" ]; then
  CHORUZ_OPERATOR_PASSWORD="$CHORUZ_OPERATOR_PASSWORD_OVERRIDE"
fi
NEW_CREDS=false
if [ -z "${CHORUZ_SESSION_SECRET:-}" ]; then
  CHORUZ_SESSION_SECRET=$(openssl rand -hex 32)
  NEW_CREDS=true
fi
if [ -z "${CHORUZ_OPERATOR_PASSWORD:-}" ]; then
  CHORUZ_OPERATOR_PASSWORD=$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-24)
  NEW_CREDS=true
fi
export CHORUZ_SESSION_SECRET CHORUZ_OPERATOR_PASSWORD
export CHORUZ_REMOTE_CONTROL_GATEWAY_URL CHORUZ_REMOTE_CONTROL_GATEWAY_SECRET
if [ "$NEW_CREDS" = true ]; then
  umask 077
  {
    printf '# Generated by infra/host/dev.sh on %s. DO NOT COMMIT.\n' "$(date)"
    printf '# Sourced by dev.sh on subsequent runs. Override by exporting before running.\n'
    printf 'export CHORUZ_SESSION_SECRET=%q\n' "$CHORUZ_SESSION_SECRET"
    printf 'export CHORUZ_OPERATOR_PASSWORD=%q\n' "$CHORUZ_OPERATOR_PASSWORD"
  } > "$DEV_ENV_FILE"
  chmod 600 "$DEV_ENV_FILE"
  echo -e "${GREEN}Generated dev credentials → ${DEV_ENV_FILE}${NC}"
  echo -e "${YELLOW}  Login: ${CHORUZ_OPERATOR_USER:-operator} / ${CHORUZ_OPERATOR_PASSWORD}${NC}"
fi

# 1. Start PostgreSQL
echo -e "${YELLOW}[1/4] Starting PostgreSQL...${NC}"
pnpm host:start

# 2. Build
if [[ "${CHORUZ_SKIP_BUILD:-0}" == "1" ]]; then
  echo -e "${YELLOW}[2/4] Using prebuilt Rust binaries...${NC}"
else
  echo -e "${YELLOW}[2/4] Building Rust binaries...${NC}"
  cargo build --release
fi

# 2.5. Run database migrations
if [[ "${CHORUZ_SKIP_MIGRATIONS:-0}" == "1" ]]; then
  echo -e "${YELLOW}[2.5/4] Database migrations already applied...${NC}"
else
  echo -e "${YELLOW}[2.5/4] Running database migrations...${NC}"
  pnpm db:migrate
fi

# Bind host — defaults to 127.0.0.1 (localhost-only). Set CHORUZ_BIND_HOST=0.0.0.0
# to expose to LAN (e.g. mobile on same WiFi); only do this with strong creds set.
BIND_HOST="${CHORUZ_BIND_HOST:-${CHORUZ_API_HOST}}"
API_CONNECT_HOST="${BIND_HOST}"
if [ "${API_CONNECT_HOST}" = "0.0.0.0" ]; then
  API_CONNECT_HOST="127.0.0.1"
fi
API_BASE_URL="http://${API_CONNECT_HOST}:${API_PORT}"
WEB_BASE_URL="http://${API_CONNECT_HOST}:${WEB_PORT}"
CODEX_RUNTIME_DIR="${CHORUZ_CODEX_RUNTIME_DIR:-${TMPDIR:-/tmp}/choruz-codex-runtime-$(id -u)-$(printf '%s' "${ROOT_DIR}" | cksum | awk '{print $1}')}"

if [ -f "${WATCHDOG_RECORD}" ]; then
  OLD_WATCHDOG_PID=$(read_process_record_pid "${WATCHDOG_RECORD}")
  if [ -n "${OLD_WATCHDOG_PID}" ] && kill -0 "${OLD_WATCHDOG_PID}" 2>/dev/null; then
    if process_record_matches "${WATCHDOG_RECORD}" '^n.*/infra/host/pipeline_watchdog\.sh$'; then
      stop_owned_process "${OLD_WATCHDOG_PID}" '^n.*/infra/host/pipeline_watchdog\.sh$' || true
      echo -e "${YELLOW}  Stopped stale pipeline watchdog (PID ${OLD_WATCHDOG_PID})${NC}"
    else
      echo -e "${YELLOW}  Ignored stale watchdog pid that does not match this worktree (PID ${OLD_WATCHDOG_PID})${NC}"
    fi
  fi
  rm -f "${WATCHDOG_RECORD}"
fi

# 3. Start API Gateway
echo -e "${YELLOW}[3/4] Starting API Gateway (port ${API_PORT}, host ${BIND_HOST})...${NC}"
nohup env \
  CHORUZ_DATABASE_URL="${DB_URL}" \
  CHORUZ_INTERNAL_API_URL="${API_BASE_URL}" \
  CHORUZ_INTERNAL_WEB_URL="${WEB_BASE_URL}" \
  CHORUZ_ATTACHMENT_DIR=".choruz-runtime/attachments" \
  CHORUZ_RUNTIME_DIR="${CODEX_RUNTIME_DIR}" \
  CHORUZ_API_HOST="${BIND_HOST}" CHORUZ_API_PORT="${API_PORT}" \
  ./target/release/choruz-api-gateway >"${LOG_DIR}/api-gateway.log" 2>&1 &
API_PID=$!
echo "  API Gateway PID: $API_PID"

# 4. Start Pipeline (WebSocket fanout, port 3020)
echo -e "${YELLOW}[4/4] Starting Pipeline (port ${PIPELINE_PORT}, host ${BIND_HOST})...${NC}"
nohup env \
  CHORUZ_DATABASE_URL="${DB_URL}" \
  CHORUZ_API_BASE_URL="${API_BASE_URL}" \
  CHORUZ_WEB_BASE_URL="${WEB_BASE_URL}" \
  CHORUZ_PIPELINE_METRICS_PORT="${PIPELINE_PORT}" \
  CHORUZ_PIPELINE_METRICS_HOST="${BIND_HOST}" \
  ./target/release/choruz-pipeline >"${LOG_DIR}/choruz-pipeline.log" 2>&1 &
PIPELINE_PID=$!
echo "  Pipeline PID: $PIPELINE_PID"

# Save PIDs for stop script
if ! write_process_record "${API_RECORD}" "$API_PID" || ! write_process_record "${PIPELINE_RECORD}" "$PIPELINE_PID"; then
  echo -e "${RED}ERROR: Could not create owned process records${NC}"
  stop_owned_process "${PIPELINE_PID}" "${PIPELINE_PROCESS_REGEX}" || true
  stop_owned_process "${API_PID}" "${API_PROCESS_REGEX}" || true
  rm -f "${API_RECORD}" "${PIPELINE_RECORD}"
  exit 1
fi

# Health checks
echo "Waiting for services to be ready..."
if ! wait_for_service_ready "${API_PID}" "${API_PROCESS_REGEX}" "http://127.0.0.1:${API_PORT}/readyz" "choruz-api-gateway" "${BACKEND_READY_ATTEMPTS}"; then
  echo -e "${RED}ERROR: API Gateway failed to start within ${BACKEND_READY_TIMEOUT_SECONDS}s${NC}"
  stop_owned_process "${PIPELINE_PID}" "${PIPELINE_PROCESS_REGEX}" || true
  stop_owned_process "${API_PID}" "${API_PROCESS_REGEX}" || true
  echo "Retry with the printed config or run the gateway in the foreground for logs."
  exit 1
fi
echo "  API Gateway ready"

if ! wait_for_service_ready "${PIPELINE_PID}" "${PIPELINE_PROCESS_REGEX}" "http://127.0.0.1:${PIPELINE_PORT}/readyz" "choruz-pipeline" "${BACKEND_READY_ATTEMPTS}"; then
  echo -e "${RED}ERROR: Pipeline failed to start within ${BACKEND_READY_TIMEOUT_SECONDS}s${NC}"
  stop_owned_process "${PIPELINE_PID}" "${PIPELINE_PROCESS_REGEX}" || true
  stop_owned_process "${API_PID}" "${API_PROCESS_REGEX}" || true
  exit 1
fi
echo "  Pipeline ready"

# Start pipeline watchdog — only restart if process is dead (not on 503).
# Pipeline reports 503 when no runners are connected; the pipeline itself
# handles delivery via headless --print mode, so that condition is expected.
nohup env \
  CHORUZ_DATABASE_URL="${DB_URL}" \
  CHORUZ_API_BASE_URL="${API_BASE_URL}" \
  CHORUZ_WEB_BASE_URL="${WEB_BASE_URL}" \
  CHORUZ_PIPELINE_METRICS_PORT="${PIPELINE_PORT}" \
  CHORUZ_PIPELINE_METRICS_HOST="${BIND_HOST}" \
  bash "${ROOT_DIR}/infra/host/pipeline_watchdog.sh" "${ROOT_DIR}" \
  >"${LOG_DIR}/pipeline-watchdog.log" 2>&1 &
WATCHDOG_PID=$!
if ! write_process_record "${WATCHDOG_RECORD}" "$WATCHDOG_PID"; then
  echo -e "${RED}ERROR: Could not create watchdog process record${NC}"
  stop_owned_process "${WATCHDOG_PID}" '^n.*/infra/host/pipeline_watchdog\.sh$' || true
  exit 1
fi

echo ""
echo -e "${GREEN}All services started!${NC}"
echo "  API Gateway: http://127.0.0.1:${API_PORT}"
echo "  Pipeline:    http://127.0.0.1:${PIPELINE_PORT} (with watchdog)"
echo "  Logs:        ${LOG_DIR}"
echo ""
echo "To start the web UI:"
echo "  pnpm dev:web"
echo ""
echo "To stop all services:"
echo "  ./infra/host/dev_stop.sh"
echo ""
echo "Login: ${CHORUZ_OPERATOR_USER:-operator} / ${CHORUZ_OPERATOR_PASSWORD}"
